#!/bin/bash
bspc monitor HDMI-A-0 -d 4 5 6
bspc monitor DisplayPort-0 -d 1 2 3
bspc monitor DVI-D-0 -d 7 8 9

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Steam follow=off
bspc rule -a Discord follow=off
bspc rule -a Polybar layer=below
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# Boder's colors
bspc config focused_border_color "#98b6d0"
bspc config normal_border_color "#2e3436"

# rounded corners
bspc config border_radius 12

# compositor
killall picom
picom &

# Shortkeys
killall sxhkd
sxhkd &

# Set the cool cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
$HOME/.config/nitrogen/time_wallpaper.sh &

# Launching the bar
killall polybar
polybar -c .config/polybar/config center &
polybar -c .config/polybar/config left &
polybar -c .config/polybar/config right &

# Merging Xressources
xrdb -merge /home/leo/.Xresources

# Start pulseaudio
start-pulseaudio-x11

# Start dunst
killall dunst
dunst -config $HOME/.config/dunst/dunstrc &

# putting the bars under everything
for bar in $(xdo id -N Polybar); do
    xdo below -t $(xdo id -n root) $bar
done

# redshift
killall redshift
redshift -P -l 47:6 &

# numlock
numlockx on
